directories:
  output: release
  buildResources: build
appId: com.devdussey.purge
productName: Purge
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - scripts/**/*
publish:
  provider: github
  owner: devdussey
  repo: Purge
  releaseType: release
win:
  target: nsis
  icon: public/purge-icon.ico
  requestedExecutionLevel: requireAdministrator
  publisherName: DevDussey
mac:
  target: dmg
  icon: public/PurgedIcon.png
linux:
  target: AppImage
  icon: public/PurgedIcon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  deleteAppDataOnUninstall: false
  shortcutName: Purge Antivirus
  runAfterFinish: true
  menuCategory: true
  displayLanguageSelector: false
  installerLanguages:
    - en_US
  perMachine: true
  allowElevation: true
  license: LICENSE.txt
electronVersion: 28.3.3
