directories:
  output: release
  buildResources: build
appId: com.devdussey.purge
productName: Purge by DevDussey
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - scripts/**/*
publish:
  provider: github
  owner: devdussey
  repo: Purge
  releaseType: release
win:
  target: nsis
  icon: public/PurgedIcon.png
  requestedExecutionLevel: requireAdministrator
  publisherName: DevDussey
mac:
  target: dmg
  icon: public/PurgedIcon.png
linux:
  target: AppImage
  icon: public/PurgedIcon.png
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 28.3.3
